#!/usr/bin/env python3
"""
Regenerate the SCENTS and PRESETS data blocks inside docs/data.js.

SCENTS are loaded from scents.json and PRESETS are loaded from presets/.
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRESET_GLOB = os.path.join(ROOT, "presets", "**", "*.json")
SCENTS_FILE = os.path.join(ROOT, "scents.json")
DATA_FILE = os.path.join(ROOT, "docs", "data.js")

SCENTS_START = "// SCENTS:START"
SCENTS_END = "// SCENTS:END"
START = "// PRESETS:START"
END = "// PRESETS:END"

EMOJIS = {
    "bakery": "🍞", "brakes": "🏎️", "cave": "🦇", "coffee": "☕",
    "desert": "🏜️", "dirt": "🌍", "energy": "⚡", "flowers": "🌸",
    "forest": "🌲", "grass": "🌿", "gunpowder": "💥", "hay": "🌾",
    "health": "💚", "leather": "🐄", "leaves": "🍂", "new-car": "🚗",
    "perfume": "💐", "rain": "🌧️", "sea": "🌊", "smoke": "🔥",
    "snow": "❄️", "temple": "🏛️", "victory": "🏆",
}

CATEGORY_EMOJIS = {
    "action": "💥", "food": "🍽️", "fantasy": "✨", "material": "🧱",
    "mechanical": "⚙️", "nature": "🌿", "social": "🎉",
}


def collect():
    entries = []
    for path in sorted(glob.glob(PRESET_GLOB, recursive=True)):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        name = data.get("name") or os.path.basename(path)
        file = os.path.relpath(path, os.path.join(ROOT, "presets")).replace(os.sep, "/")
        entries.append((name, file))
    # sort case-insensitive by display name
    entries.sort(key=lambda e: e[0].lower())
    return entries


def collect_scents():
    with open(SCENTS_FILE, "r", encoding="utf-8") as f:
        return json.load(f).get("scents", [])


def render_scents(scents):
    lines = [
        f"{SCENTS_START} -- auto-generated by scripts/generate_docs_data.py, do not edit by hand",
        "const SCENTS = [",
    ]
    for scent in scents:
        item = {
            "id": scent["id"],
            "name": scent["name"],
            "emoji": EMOJIS.get(scent["id"], CATEGORY_EMOJIS.get(scent["category"], "✨")),
            "color": scent["color"],
            "category": scent["category"],
            "desc": scent["description"],
        }
        fields = ", ".join(
            f"{key}:{json.dumps(value, ensure_ascii=False)}"
            for key, value in item.items()
        )
        lines.append(f"  {{{fields}}},")
    lines.append("];\n" + SCENTS_END)
    return "\n".join(lines)


def render(entries):
    lines = [
        f"{START} -- auto-generated by scripts/generate_docs_data.py, do not edit by hand",
        "const PRESETS = [",
    ]
    for name, file in entries:
        n = json.dumps(name, ensure_ascii=False)
        f = json.dumps(file, ensure_ascii=False)
        lines.append(f"  [{n}, {f}],")
    lines.append("];")
    lines.append(END)
    return "\n".join(lines)


def main():
    if not os.path.exists(DATA_FILE):
        print(f"::error::{DATA_FILE} not found")
        return 1

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    for block_start, block_end in ((SCENTS_START, SCENTS_END), (START, END)):
        if not re.search(rf"{re.escape(block_start)}.*?{re.escape(block_end)}", content, re.DOTALL):
            print(f"::error::Markers '{block_start}' / '{block_end}' not found in docs/data.js")
            return 1

    scents = collect_scents()
    entries = collect()
    new_content = re.sub(
        rf"{re.escape(SCENTS_START)}.*?{re.escape(SCENTS_END)}",
        render_scents(scents),
        content,
        flags=re.DOTALL,
    )
    new_content = re.sub(
        rf"{re.escape(START)}.*?{re.escape(END)}",
        render(entries),
        new_content,
        flags=re.DOTALL,
    )

    if new_content == content:
        print(f"docs/data.js already up to date — {len(scents)} scent(s), {len(entries)} preset(s)")
        return 0

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated docs/data.js — {len(scents)} scent(s), {len(entries)} preset(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
