#!/usr/bin/env python3
"""
Regenerate the PRESETS array inside docs/data.js by scanning presets/.

The script only replaces the block between the markers
    // PRESETS:START
    // PRESETS:END
so the manually curated SCENTS list above stays untouched.
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRESET_GLOB = os.path.join(ROOT, "presets", "sb-preset-*.json")
DATA_FILE = os.path.join(ROOT, "docs", "data.js")

START = "// PRESETS:START"
END = "// PRESETS:END"


def collect():
    entries = []
    for path in sorted(glob.glob(PRESET_GLOB)):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        name = data.get("name") or os.path.basename(path)
        entries.append((name, os.path.basename(path)))
    # sort case-insensitive by display name
    entries.sort(key=lambda e: e[0].lower())
    return entries


def render(entries):
    lines = [
        f"{START} -- auto-generated by scripts/generate_docs_data.py, do not edit by hand",
        "const PRESETS = [",
    ]
    for name, file in entries:
        n = json.dumps(name, ensure_ascii=False)
        f = json.dumps(file, ensure_ascii=False)
        lines.append(f"  [{n}, {f}],")
    lines.append("];")
    lines.append(END)
    return "\n".join(lines)


def main():
    if not os.path.exists(DATA_FILE):
        print(f"::error::{DATA_FILE} not found")
        return 1

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    pattern = re.compile(
        rf"{re.escape(START)}.*?{re.escape(END)}",
        re.DOTALL,
    )
    if not pattern.search(content):
        print(f"::error::Markers '{START}' / '{END}' not found in docs/data.js")
        return 1

    entries = collect()
    new_block = render(entries)
    new_content = pattern.sub(new_block, content)

    if new_content == content:
        print(f"docs/data.js already up to date — {len(entries)} preset(s)")
        return 0

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated docs/data.js — {len(entries)} preset(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
